version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    deploy:
      mode: global
    hostname: tl-rabbit
    ports:
      - "5672:5672"
      - "8087:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      DOCKER_HOST: "tcp://localhost:2375" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
